spring:
  application:
    name: users
  redis:
    host: localhost
    password:
    port: 6379
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session
    store-type: redis
security:
  sessions: NEVER
server:
  servlet:
    session:
      timeout: 3600s
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
db:
  driver: org.postgresql.Driver
  hostname: localhost
  database: desafio
  username: postgres
  password: "01020304"
  port: 5432
  url: jdbc:postgresql://${db.hostname}:${db.port}/${db.database}
  hibernate:
    showSql: true
    formatSql: true
    ddlAuto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
